# Generated by Django 3.1 on 2020-08-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoclasses',
            name='course_number',
        ),
    ]
