# Generated by Django 3.1 on 2020-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cyberSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('course_number', models.IntegerField(max_length=60)),
                ('instructor_name', models.CharField(max_length=60)),
                ('duration', models.FloatField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='graphicDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='helpDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=60)),
            ],
        ),
    ]
